# Generated by Django 4.1.1 on 2022-09-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkeatEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("word_image_url", models.URLField()),
                ("page_number", models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkeatPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.SmallIntegerField(verbose_name="Page Number")),
                ("image_link", models.URLField()),
                (
                    "first_keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_keyword",
                        to="words.skeatentry",
                    ),
                ),
                (
                    "second_keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_keyword",
                        to="words.skeatentry",
                    ),
                ),
            ],
        ),
    ]
