# Generated by Django 4.1.1 on 2022-09-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skeatentry",
            name="not_in_main_skeat",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="skeatentry",
            name="word_image_url",
            field=models.URLField(null=True),
        ),
    ]
